title: Isthmus Carshare
email: isthmuscarshare@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  An affordable, member-owned, and community-oriented alternative to private car ownership 
  in Madison that will enhance mobility and transportation equity in our city, reduce congestion, 
  and promote environmental stewardship
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

exclude:
  - .jekyll-cache/
  - gemfiles/
  - .github/
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock
